version: '3.9'

services:
  app:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    volumes:
      - ../:/app/
    container_name: app
    ports:
      - "5000:5000"
    command: >
      sh -c "coverage run -m pytest -v"
